(require 'ert)
(require 'jira-markup-mode)

(ert-deftest jira-markup-regex-header-1-test ()
  (should (string-match-p jira-markup-regex-header-1 "h1. "))
  (should (string-match-p jira-markup-regex-header-1 "h1. Header"))
;;  (should (string-match-p jira-markup-regex-header-1 "   h1.    Header   "))
  (should-not (string-match-p jira-markup-regex-header-1 "a h1. Header"))
  (should-not (string-match-p jira-markup-regex-header-1 " a h1. Header")))

(ert-deftest jira-markup-regex-header-2-test ()
  (should (string-match-p jira-markup-regex-header-2 "h2. "))
  (should (string-match-p jira-markup-regex-header-2 "h2. Header"))
  (should-not (string-match-p jira-markup-regex-header-2 "a h2. Header"))
  (should-not (string-match-p jira-markup-regex-header-2 " a h2. Header")))

(ert-deftest jira-markup-regex-blockquote-test ()
  (should (string-match-p jira-markup-regex-blockquote "bq. "))
  (should (string-match-p jira-markup-regex-blockquote "  bq.  "))
  (should (string-match-p jira-markup-regex-blockquote "bq. the-quote"))
;;  (should (string-match-p jira-markup-regex-blockquote "  bq.   the-quote  "))
  (should-not (string-match-p jira-markup-regex-blockquote "a bq. the-quote")))

(ert-deftest jira-markup-regex-hr-test ()
  (should (string-match-p jira-markup-regex-hr "----"))
  (should (string-match-p jira-markup-regex-hr "  ----"))
  (should-not (string-match-p jira-markup-regex-hr "---"))
  (should-not (string-match-p jira-markup-regex-hr "-----")))
